### ISSUE TITLE
Failed Assertion: boolean expression must not be null;

### ISSUE THREAD

**Issue by iLolz** [parse-community/Parse-SDK-Flutter#282] opened 2019-10-31 14:53 UTC
I use the B4a in one app and the parse_server_sdk is allright, but in a new project when I try to get a class objects or upload any new object I received the error : "Failed assertion: boolean expression must not be null!", when I debug the error whas inside the parse_server_sdk, I redo all my Parse().initialize() and other lines of code trying concert that but nothing happen. I created a new project and tried to connect and the same error happens...

**Comment by phillwiggins** [comment] 2019-10-31 14:55
Hey

It's difficult to understand what the issue is without seeing a bit more code or a few more details. Do you have any code you can provide?

**Comment by iLolz** [comment] 2019-11-01 00:17
![Captura de Tela 2019-10-31 às 16 50 23](https://user-images.githubusercontent.com/30672948/67983579-c020fe80-fc03-11e9-8d08-9d72594a225f.png)
![Captura de Tela 2019-10-31 às 16 50 44](https://user-images.githubusercontent.com/30672948/67983592-c8793980-fc03-11e9-859d-336c9c1c3151.png)
![Captura de Tela 2019-10-31 às 16 50 58](https://user-images.githubusercontent.com/30672948/67983602-cc0cc080-fc03-11e9-8673-e0f5eecd0371.png)
It's happen in two new projects, I was do the same way was doing in the previous but this error has occurred in both new attempts... when I use cURL commands it's all executing correctly... so it's not a problema on my B4A...

**Comment by iLolz** [comment] 2019-11-07 14:53
The problem was in the atualization, before he uses shared_preferences, in new versions the package changes, my function can't access the varible named "data" and nothing happens, in a  error on downgrade parse_server_sdk version (i'm using the caracter "^" in my dependencies version and using this, Flutter get any version after the version i'm define, when I do that, the downgrade don't ocurred and i'm still use the parse_server_sdk version 1.0.24, when I change all happens again, because I put "^1.0.21", now I;m using "1.0.21",),  It's something diferent in the implementation of the parse_server_sdk between versions 1.0.21 and 1.0.24, think thats ocurred througth change of "shared_preferences" to the new package... thank's for the atention!

**Comment by gorillatapstudio** [comment] 2020-05-12 02:05
I have the same error msg with the latest version. All works for ios and android but for web app, it failed when i call the user.signup() function. The bug is confirmed with many repeated tests.

**Comment by RodrigoSMarques** [comment] 2021-02-19 13:04
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.

**Closed by RodrigoSMarques** 2021-02-19 13:04 UTC
