### ISSUE TITLE
Unable to access Parse Server on the macOS platform

### ISSUE THREAD

**Issue by ManasMalla** [parse-community/Parse-SDK-Flutter#677] opened 2021-09-28 08:08 UTC
I recently migrated to Flutter from the Android platform, and I'm a user of Parse from about 2-3yrs and have been able to use Parse SDK without any issue on the Android Platform and it even works when using the Parse-SDK-Flutter on Android, (even on Web platform) but on the macOS platform it doesn't seem to initialise Parse. I tried to check if Parse was initialised with `Parse().hasParseBeenInitialized()` but that returns false. This is my code for the initialisation - 
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Parse().initialize("myappID", ".....",
      clientKey: ".....",
      autoSendSessionId: true,
      coreStore: await CoreStoreSembastImp.getInstance(),
      debug: true);

  runApp(const DucksInARowApp());
}
```
I received the error : 
```
....
 [!] CocoaPods could not find compatible versions for pod "connectivity_plus_macos":
      In Podfile:
        connectivity_plus_macos (from `Flutter/ephemeral/.symlinks/plugins/connectivity_plus_macos/macos`)

    Specs satisfying the `connectivity_plus_macos (from `Flutter/ephemeral/.symlinks/plugins/connectivity_plus_macos/macos`)` dependency were found, but they required a higher minimum deployment target.

...
```
But i fixed it by changing the deplyment target in the podfile and runner.xcworkspace. Could you please help me out with this?

**Comment by RodrigoSMarques** [comment] 2021-10-02 11:49
Duplicate of #673 

The problem is in the 'connectivity_plus_macos' package and in the Pase package

**Comment by mtrezza** [comment] 2021-10-07 18:48
Closing as this does not seem to be an issue of the Parse Flutter SDK.

**Closed by mtrezza** 2021-10-07 18:48 UTC
Labels: question
