### ISSUE TITLE
Specify email address in LoginWith 

### ISSUE THREAD

**Issue by Chralu** [parse-community/Parse-SDK-Flutter#506] opened 2020-11-13 13:39 UTC
Hi,

when login with an third party auh service for the first time, I would like to set email without triggering email verification.
Indeed, `email` should already be verified by upstream third auth service 

We could modify the `loginWith` method :
```
ParseUser.loginWith(String provider, AuthData authData, {String email});
```

That way, `email` is set during the `POST /parse/users`, and email verification is not triggered.

Any thoughts about that ?

**Comment by Danaru87** [comment] 2020-11-13 14:13
# In Parse Server REST GUIDE
there are two methods to register user with third party provider:

## POST /parse/user
Sending only authData in body request, this will create a new user with random username, random password. Other user's properties are ignored.

## POST /parse/user
Sendind json body containing user's properties AND authData property, this will create a new user linked to third party provider, setting all properties set in json body into user's record.

### Example:

**Register only with AutData:**

**Request**
```
curl --request POST \
  --url https://{parseServerUrl}/parse/users \
  --header 'Content-Type: application/json' \
  --header 'X-Parse-Application-Id: {appId}' \
  --data '{"authData":{"provider":{"access_token":"accessToken","id":"id","id_token":"id_token"}}}'
```
**Result**
created user as json:
```json
{
"objectId":"objectId",
"username":"generated",
"password":"*********",
"email": "undefined",
"authData":{"authData":{"provider":{"access_token":"accessToken","id":"id","id_token":"id_token"}}},
"emailVerified": "undefined",
"updatedAt": "....",
"createdAt": ".....",
"ACL": "...."
}
```

**Register AutData and User properties:**

**Request**
```curl
curl --request POST \
  --url https://{parseServerUrl}/parse/users \
  --header 'Content-Type: application/json' \
  --header 'X-Parse-Application-Id: {appId}' \
  --data '{
"username":"username",
"password":"password",
	"email": "email@email.io",
	"authData":{"google": {"access_token":"accessToken", "id":"id", "id_token": "idToken"}}
}'
```
**Result**
created user as json:
```json
{
"objectId":"objectId",
"username":"username",
"password":"*********",
"email": "email@email.io",
"authData":{"google": {"access_token":"accessToken", "id":"id", "id_token": "idToken"}},
"emailVerified": "undefined",
"updatedAt": "....",
"createdAt": ".....",
"ACL": "...."
}
```

# In Parse SDK 

In dart/flutter SDK, only **Register with AutData** is possible.
It can be a problem. In our app, we need to set user's email from google or facebook.
To do that, we update the user setting email BUT this trigger emailVerification (and we don't want verification for user from third party providers) .

To respect REST guide, i think we must do something like this:

ParseUser::loginWith
Should take an optional params {String email, String username, String password};
Then create a new user with ParseUser.createUser(username, password, email);

ParseUser::_loginWith
Should send in body request toJson() and authData, not only authData.

I'm testing it on our fork, we will do a PR when it's ok for us.

**Comment by RodrigoSMarques** [comment] 2021-02-19 13:28
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.

**Closed by RodrigoSMarques** 2021-02-19 13:28 UTC

**Comment by keanallen** [comment] 2021-08-14 12:00
loginWith('facebook', authData) also gives me an error: `Facebook auth is invalid for this user`. What should I do? I am using the latest version of parse_server_flutter

**Comment by RodrigoSMarques** [comment] 2021-08-14 15:58
The problem is not in the package. 

Android or iOS project?

 it is some wrong or not done configuration in the Back4app or in your project.

check all configurations.

**Comment by RodrigoSMarques** [comment] 2021-08-14 15:59
The problem is not in the package.

Android or iOS project?

it is some wrong or not done configuration in the Back4app or in your project.

check all configurations.

**Comment by keanallen** [comment] 2021-08-14 16:06
Yes. I think the problem is in back4app loginWith. As far as i know, all
configuration are correct. Their support team is unresponsive at the moment

**Comment by RodrigoSMarques** [comment] 2021-08-14 16:13
I have two projects set up with Facebook in Back4app working (including the one in the guide)

Delete Facebook App Id and add again.

Retest.
