### ISSUE TITLE
ParseUser(...).login() returns a ParseResponse with null fields on web with Back4App database

### ISSUE THREAD

**Issue by perilousGourd** [parse-community/Parse-SDK-Flutter#564] opened 2021-02-12 09:46 UTC
Thank you for writing this awesome library that I anticipate will help me a lot.

**Issue:** Trying to log in a user in web results in a ParseResponse with null fields (sign up succeeds):

```
successful signUp response with user =
{"className":"_User","objectId":"ZAdWIWNPRS","createdAt":"2021-02-12T09:23:37.626Z","username":"pls
work@gmail.com","email":"plswork@gmail.com","sessionToken":"r:1bcaf2a02519a2fd80bc950f641a9fcf"}

╭-- Parse Request
curl -X GET -H 'X-Parse-Revocable-Session: 1' -H 'X-Parse-Installation-Id:
98447c18-6bec-47b8-8663-1a200bb71cab' -H 'content-type: null' -H 'X-Parse-Application-Id:
o5AkhnGifXHqF1dUETGaOoj4XO4nKscxWQdkhLsC' -H 'X-Parse-Client-Key:
ZFPzkz7dsiAhiAkswKzCHr9A9Ph6Se55aEGTtABS'
https://parseapi.back4app.com/login?username=plswork%40gmail.com&password=plswork

 https://parseapi.back4app.com/login?username=plswork@gmail.com&password=plswork
╰--
╭-- Parse Response
Class: _User
Function: ParseApiRQ.login
Status Code: null
Type: null
Exception: null
╰-- 
```

Pretty sure this is the same issue as #500, but I haven't been able to resolve it myself given the information in that thread.

I'm using Back4App. I think the equivalent of the Docker and express procedures that solved that issue would be to put
```json
{
    "allowHeaders": [
        "X-Parse-Installation-Id"
    ]
}
```
in the Back4App Custom Parse Server Options, which I've done, but the issue remains.

I might just be using the library incorrectly. In particular, following [the code for signing and logging in users in the README](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#users) gives me syntax errors in Android Studio. I experimented and found a slight modification (code below) that worked for signing up, but haven't found an equivalent modification for logging in, so this could be the cause of my issue, also.

<details>
<summary><b>Minimal working example that produces my issue. Relevant functions / functions I have least confidence in having written correctly are the first three, at the top.</b></summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';
import 'dart:ui';


void initializeParse() async {
  CoreStore coreStore;
  if (kIsWeb) {
    coreStore = await CoreStoreSembastImp.getInstance();
  } else {
    coreStore = CoreStoreMemoryImp();
  }

  await Parse().initialize(
    "o5AkhnGifXHqF1dUETGaOoj4XO4nKscxWQdkhLsC",
    "https://parseapi.back4app.com",
    clientKey: "ZFPzkz7dsiAhiAkswKzCHr9A9Ph6Se55aEGTtABS",
    appName: 'debugging_login',
    appVersion: '1.0.0',
    appPackageName: 'debugging_login',
    coreStore: coreStore,
    debug: true,
  );
}


// signUp behaves as expected
void signUp(
    {@required String username,
    @required String password,
    @required String email}) async {

  // // The approach described in the documentation, which Android
  // // Studio highlights has not being syntactically valid (for
  // // version 2.0.1, 2.0.0 and 1.0.28):
  // var user = ParseUser().create(username, password, email);
  // var response = await user.signUp();

  ParseUser user = ParseUser(username, password, email);
  ParseResponse response = await user.create();
  if (response.success) {
    user = response.result;
    print('successful signUp response with user = ' + user.toString());
  } else {
    print('signUp response has error = ' + response.error.toString());
  }
}

// logIn does not behave as expected
void logIn(
    {@required String username,
    @required String password,
    @required String email}) async {

  // // The approach described in the documentation, which Android
  // // Studio highlights has not being syntactically valid (for
  // // version 2.0.1, 2.0.0 and 1.0.28):
  // var user = ParseUser().create(username, password, email);
  // var response = await user.login();

  ParseUser user = ParseUser(username, password, email);
  ParseResponse response = await user.login();

  if (response.success) {
    user = response.result;
    print('successful logIn response with user = ' + user.toString());
  } else {
    print('logIn response has error = ' + response.error.toString());
  }
}

// ---------------- UI, behaving as expected -----------------

void main() {
  runApp(
    DebuggingLogin(),
  );
}

class DebuggingLogin extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    initializeParse();

    return MediaQueryDirectionality(
      child: SignUpLogInView(),
    );
  }
}

class SignUpLogInView extends StatefulWidget {
  @override
  _SignUpLogInViewState createState() => _SignUpLogInViewState();
}

class _SignUpLogInViewState extends State<SignUpLogInView> {
  FocusNode focusNodePassword;
  FocusNode focusNodeEmail;

  TextEditingController controllerEmail;
  TextEditingController controllerPassword;

  @override
  void initState() {
    super.initState();
    focusNodeEmail =
        FocusNode(onKey: (FocusNode focusNode, RawKeyEvent rawKeyEvent) {
      if (rawKeyEvent is RawKeyDownEvent &&
          rawKeyEvent.logicalKey == LogicalKeyboardKey.tab &&
          !rawKeyEvent.isShiftPressed) {
        focusNodePassword.requestFocus();
        return true;
      }
      return false;
    });

    focusNodePassword =
        FocusNode(onKey: (FocusNode focusNode, RawKeyEvent rawKeyEvent) {
      if (rawKeyEvent is RawKeyDownEvent &&
          rawKeyEvent.logicalKey == LogicalKeyboardKey.tab &&
          rawKeyEvent.isShiftPressed) {
        focusNodeEmail.requestFocus();
        return true;
      }
      return false;
    });

    controllerEmail = TextEditingController();
    controllerPassword = TextEditingController();
  }

  @override
  void dispose() {
    focusNodeEmail.dispose();
    focusNodePassword.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: [
          SizedBox(
            height: 40,
          ),
          LabelledEntryStrip(
            label: 'email',
            focusNode: focusNodeEmail,
            controller: controllerEmail,
          ),
          SizedBox(
            height: 20,
          ),
          LabelledEntryStrip(
            label: 'password',
            focusNode: focusNodePassword,
            controller: controllerPassword,
          ),
          SizedBox(
            height: 20,
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Button(
                label: 'sign up',
                onTap: () => signUp(
                    username: controllerEmail.text,
                    password: controllerPassword.text,
                    email: controllerEmail.text),
              ),
              SizedBox(
                width: 10,
              ),
              Button(
                label: 'log in',
                onTap: () => logIn(
                  username: controllerEmail.text,
                  password: controllerPassword.text,
                  email: controllerEmail.text,
                ),
              ),
            ],
          )
        ],
      ),
    );
  }
}

class LabelledEntryStrip extends StatelessWidget {
  final String label;
  final FocusNode focusNode;
  final TextEditingController controller;
  LabelledEntryStrip(
      {@required this.label,
      @required this.focusNode,
      @required this.controller});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.fromLTRB(10, 0, 10, 0),
      child: Row(
        children: [
          Expanded(
            flex: 1,
            child: Text(
              label,
              style: kTextStyle,
              textAlign: TextAlign.right,
            ),
          ),
          SizedBox(
            width: 20,
          ),
          Expanded(
            flex: 5,
            child: GestureDetector(
              onTap: () {
                focusNode.requestFocus();
              },
              child: Container(
                color: white.withOpacity(0.2),
                padding: EdgeInsets.all(10),
                child: EntryEditable(
                  focusNode: focusNode,
                  controller: controller,
                ),
              ),
            ),
          ),
          Expanded(
            flex: 1,
            child: Container(),
          ),
        ],
      ),
    );
  }
}

class EntryEditable extends EditableText {
  final FocusNode focusNode;
  final TextEditingController controller;

  EntryEditable({@required this.focusNode, @required this.controller})
      : super(
          focusNode: focusNode,
          controller: controller,
          cursorColor: white,
          backgroundCursorColor: white,
          maxLines: 1,
          style: TextStyle(color: white),
          autofocus: true,
        );
}

class Button extends StatelessWidget {
  final String label;
  final Function onTap;

  Button({@required this.label, @required this.onTap});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        onTap();
      },
      child: Container(
        color: white.withOpacity(0.3),
        padding: EdgeInsets.all(10),
        child: Text(label, style: kTextStyle),
      ),
    );
  }
}

class MediaQueryDirectionality extends StatelessWidget {
  final Widget child;
  MediaQueryDirectionality({@required this.child});

  @override
  Widget build(BuildContext context) {
    MediaQueryData mediaQueryData = MediaQueryData.fromWindow(window);
    return MediaQuery(
      data: mediaQueryData,
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: Container(color: grey, child: child),
      ),
    );
  }
}

const Color white = Color(0xFFFFFFFF);
const Color grey = Color(0xFF222222);
const kTextStyle = TextStyle(color: white);
```

</details>

**Comment by RodrigoSMarques** [comment] 2021-02-19 13:54
Does the problem still persist? Can we close this issue?

**Comment by perilousGourd** [comment] 2021-02-19 21:40
Problem persists, sorry (have been using linux-desktop as device in meantime). Any assistance appreciated.

**Comment by RodrigoSMarques** [comment] 2021-02-19 21:53
Check this comment

https://github.com/parse-community/Parse-SDK-Flutter/issues/490#issuecomment-714588980

**Comment by ken1020** [comment] 2021-02-22 08:20
found this issue only in "Back4App".
if "Sashido", no errors!

**Comment by RodrigoSMarques** [comment] 2021-02-22 12:41
Excellent. So the problem is not with the package. I suggest opening an issue on the Back4app support.

**Comment by perilousGourd** [comment] 2021-02-23 03:50
`doNotSendInstallationId = true` as described in linked threads worked! :D

> I suggest opening an issue on the Back4app support.

I'll look into this.

Thank you!

**Closed** 2021-02-23 03:51 UTC

**Comment by ken1020** [comment] 2021-03-06 04:34
Hi, Back4App done fix this!
