### ISSUE TITLE
ParseLiveListWidget doesn't work

### ISSUE THREAD

**Issue by yp19** [parse-community/Parse-SDK-Flutter#623] opened 2021-05-08 22:41 UTC
**I am using following server and client versions**
"parse-server": "^4.5.0" (server)
parse_server_sdk_flutter: ^3.0.0  (client)

**Flutter log contains following lines (mostly)**
```
I/flutter ( 8004): LiveQuery: : Socket opened
I/flutter ( 8004): LiveQuery: : ConnectMessage: {op: connect, applicationId: appid, sessionToken: r:token}
I/flutter ( 8004): LiveQuery: : Done
I/flutter ( 8004): LiveQueryReconnectingController: Retrytimer set to 10000ms
I/flutter ( 8004): LiveQueryReconnectingController: LiveQueryClientEvent.DISCONNECTED
```

**Server log contains following lines (mostly)**
```
info: Client disconnect: undefined
error: Can not find client undefined on disconnect
```

**Flutter parse init:**
```
await Parse().initialize(
    keyParseApplicationId,
    keyParseServerUrl,
    debug: true,
    liveQueryUrl: keyLiveQueryUrl,
    coreStore: await CoreStoreSharedPrefsImp.getInstance(),
    autoSendSessionId: true,
  );
```

**Note:** The LiveQuery is working with Javascript code.

**Comment by yp19** [comment] 2021-05-08 22:42
@RodrigoSMarques Could you help with this. Thanks in advance.

**Comment by RodrigoSMarques** [comment] 2021-05-12 01:39
It is not a problem in LiveQuery because I am using it in two projects without errors.

Is the problem using ParseLiveListWidget?

I don't know what this widget does.

@fischerscode do you know what it can be?

**Comment by pastordee** [comment] 2021-05-12 04:18
It can’t be ParseLiveListWidget I’m using it and gh it works well for me.

**Comment by fischerscode** [comment] 2021-05-12 11:04
@yp19 
Please 'inspect' your web app and have a look at the network traffic ([instructions for chrome](https://developer.chrome.com/docs/devtools/network/)). Your problem might be caused by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

@yp19 @pastordee 
Please note that there is a [live query bug](https://github.com/parse-community/parse-server/issues/7340) in version 4.5.0. There might appear problems if you have multiple live queries running at once. I recommend using a custom version of 4.5.0 that contains the fix that was merged to master in [7341](https://github.com/parse-community/parse-server/pull/7341). If you want a simple solution, you could use [the version I use](https://github.com/fischerscode/parse-server/tree/4.5.0-patch1). It has been running as a the back end for a beta app for almost a month now.

**Comment by pastordee** [comment] 2021-05-12 12:05
> @yp19 
> 
> Please 'inspect' your web app and have a look at the network traffic ([instructions for chrome](https://developer.chrome.com/docs/devtools/network/)). Your problem might be caused by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
> 
> 
> 
> @yp19 @pastordee 
> 
> Please note that there is a [live query bug](https://github.com/parse-community/parse-server/issues/7340) in version 4.5.0. There might appear problems if you have multiple live queries running at once. I recommend using a custom version of 4.5.0 that contains the fix that was merged to master in [7341](https://github.com/parse-community/parse-server/pull/7341). If you want a simple solution, you could use [the version I use](https://github.com/fischerscode/parse-server/tree/4.5.0-patch1). It has been running as a the back end for a beta app for almost a month now.

Okay thanks will check it out tonight￼

**Comment by yp19** [comment] 2021-05-14 06:30
@fischerscode Thanks for the reply.

I tried your suggestion with flutter web. I have enabled CORs. It is working fine with flutter web.

But it is not working with flutter android, getting the same log repeatedly in adb log:

```
I/flutter (18510): LiveQueryReconnectingController: LiveQueryClientEvent.DISCONNECTED
I/flutter (18510): LiveQuery: : close
I/flutter (18510): LiveQuery: : Socket opened
I/flutter (18510): LiveQuery: : ConnectMessage: {op: connect, applicationId: appId, sessionToken: r:token}
I/flutter (18510): LiveQuery: : Done
I/flutter (18510): LiveQueryReconnectingController: Retrytimer set to 10000ms
I/flutter (18510): LiveQueryReconnectingController: LiveQueryClientEvent.DISCONNECTED
```

Any other ideas?

**Comment by fischerscode** [comment] 2021-05-14 08:31
@yp19 
I assume it's not working when build with `--release`.
In this case, I think it is most likely you missed [this step](https://flutter.dev/docs/development/data-and-backend/networking).

**Comment by yp19** [comment] 2021-05-14 19:33
@fischerscode 
I was not using the `--release` flag.

Without that permission set, the server was receiving connections, I able to see the log on server, I have posted the server log entries in the description.

But I have added the permission now. It's still has the same problem.

I am using firebase auth, it is working fine and also it able to load the initial list of items with a query. Only the LiveQuery is not working. Something to do with the Websocket connection.

**Comment by yp19** [comment] 2021-05-14 19:36
@fischerscode 
I have tested with `--release` flag as well. Seeing the same log.

I see the server is working from `flutter web` and regular `javascript client`.

Any ideas?

**Comment by yp19** [comment] 2021-05-20 21:07
@fischerscode Friendly ping

**Comment by fischerscode** [comment] 2021-06-09 14:25
@yp19 
Sorry, I think my GitHub notification did not work for a while.

Does the same problem appear on mobile?

Stuff, I would try:
- specify a client key
- make a minimal test project
- run a parse-server locally (rules out internet problems)

**Comment by RodrigoSMarques** [comment] 2021-07-01 23:20
Closing. No activity in the last 15 days.
If necessary open again.

**Closed by RodrigoSMarques** 2021-07-01 23:20 UTC
