### ISSUE TITLE
Custom Objects and Pointers to a CustomObject

### ISSUE THREAD

**Issue by buckettt** [parse-community/Parse-SDK-Flutter#287] opened 2019-11-09 21:09 UTC
I have a Custom Object (Activity) that I want to have a Pointer to another Custom Object (Spot).
I retrieve it as follows.

```
    queryBuilder = QueryBuilder<Activity>(Activity())
      ..orderByDescending("createdAt")
      ..includeObject([
        "mySpot", //this is the pointer
      ])
```

This works fine however mySpot is as a ParseObject whereas what I need is ParseObject as a CutomObject.

However when I setup my getter/setter for mySpot as a custom object as below

```
class Activity extends ParseObject implements ParseCloneable {
...
  static const String _keyTableName = 'Activity';
  static const String _keySpot = 'mySpot';
  
  Spot get myspot => get<Spot>(_keySpot) as Spot;
  set myspot(Spot s) => set<Spot>(_keySpot, s);
}

```

I get an error:
`type 'ParseObject' is not a subtype of type 'Spot' in type cast`

Whats the best way to cast a pointer to a custom object? Or is there a better way of doing this?

Edit: Spot extends ParseObject

**Comment by phillwiggins** [comment] 2019-11-10 08:12
Hey

It is a slight annoyance that this happens. It's mainly due to the lack of
reflection in Flutter.  I don't think there is a better version of this
right now.

**Comment by buckettt** [comment] 2019-11-10 08:49
OK thanks, I guess that means it is impossible then?

**Comment by phillwiggins** [comment] 2019-11-10 09:20
It's not impossible. How are you accessing it at the moment. Do you have a
list of 'mySpot' or just a single object. Usually single objects are fine.
It's mainly when returning a list that we found a struggle

**Comment by buckettt** [comment] 2019-11-10 09:28
'mySpot' is just a pointer to a single object. I'm accessing it using the query above then simply doing:

    var response = await queryBuilder.query();
    if (response.success) {
        var a = response.results[0].myspot;
}

**Comment by phillwiggins** [comment] 2019-11-10 09:36
Yes,  I see the issue. The problem is the list. The best thing to do is
create an empty list containing mySpot and iterate through the response
list and cast them individually. We don't have a fix for this right now but
hopefully will shortly.

**Comment by buckettt** [comment] 2019-11-10 09:50
No problem, thanks for your help.

**Closed** 2020-01-11 08:28 UTC
