### ISSUE TITLE
LiveQuery Not Working 1.0.26? ParseLiveList

### ISSUE THREAD

**Issue by pastordee** [parse-community/Parse-SDK-Flutter#330] opened 2020-03-11 09:15 UTC
LiveQuery Not Working since updating to 1.0.26 with ParseLiveList, it does not give any error.
new post and update do not take effect, is there something I have to do with LiveQuery subscription and is anyone facing the same thing.

ps, the app on 1.0.25 is working fine.

**Comment by maaeps** [comment] 2020-03-11 10:01
@pastordee 
Just to be clear:
- in your dependencies you are no longer referencing 1.0.25 but 1.0.26
- you have done no changes to your code

Indeed there are changes is LiveQuery. In the [README](https://github.com/parse-community/Parse-SDK-Flutter/blob/release/1.0.26/README.md) of 1.0.26 you can see, how you have to use it now.
Instead of `liveQuery.subscribe(query)` you have to run `liveQuery.client.subscribe(query)` this returns you a `Subscription`, on this subscription you can listen for changes.
`subscription.on(LiveQueryEvent.create, (value) {});`

ParseLiveList is just a new feature build on LiveQuery.

**Comment by pastordee** [comment] 2020-03-11 15:19
Yes everything is the same is only on one page I have added the ParseLiveList to test it, It loads the list fine but when you edit or add a new item the list don't reload,

as for the other pages, I have not touched them but LiveQuery is not working for then neither

**Comment by maaeps** [comment] 2020-03-11 16:30
Your project is not open source right? Otherwise I would have a look in the code.

It seems like the LiveQuery connection is not established.

Could you please add `debug: true,` as a parameter to your parse initialization, reinstall the app and post all logs starting with `LiveQueryReconnectingController`.

**Comment by pastordee** [comment] 2020-03-11 16:43
This is the app I don’t mind if you want to help that will be great

https://pcdl.page.link/prayers

I’m on the road now when I get home I will turn Debug

**Comment by maaeps** [comment] 2020-03-12 09:20
In case turning on debug gives us no hint, I would be happy to peak into the code.

**Comment by maaeps** [comment] 2020-03-12 11:52
On my IOS emulator, I have the same problem.
I will investigate it later.

**Comment by maaeps** [comment] 2020-03-12 13:17
The problem is a different behavior of `Connectivity().onConnectivityChanged`on Android and IOS.

**Comment by maaeps** [comment] 2020-03-12 13:32
@pastordee 
Please check out the current [release/1.0.26](https://github.com/parse-community/Parse-SDK-Flutter/tree/release/1.0.26) version.
I think it should be fixed now.

**Comment by pastordee** [comment] 2020-03-12 18:23
> @pastordee
> Please check out the current [release/1.0.26](https://github.com/parse-community/Parse-SDK-Flutter/tree/release/1.0.26) version.
> I think it should be fixed now.

Thank you so much, my live query is working and with ParseLiveListWidget<Journal> when I edit on another device it shows in debug that it has been updated but ParseLiveListWidget don't reload

**Comment by maaeps** [comment] 2020-03-12 18:42
@pastordee 
I guess `Journal` is a custom `ParseObject` class.
Please change 
`_queryBuilder = QueryBuilder(Journal())` to `_queryBuilder = QueryBuilder<Journal>(Journal())` 
and 
`ParseLiveListWidget(` to `ParseLiveListWidget<Journal>(` 
and 
`ParseLiveListElementSnapshot snapshot` to `ParseLiveListElementSnapshot<Journal> snapshot`.

Then try again and let me know if it made any difference.

**Comment by maaeps** [comment] 2020-03-12 18:49
@pastordee 
I somehow did not notice it since now.
Could you please change 1.26 in the issue title to 1.0.26?
Thanks!

**Comment by pastordee** [comment] 2020-03-12 19:36
> @pastordee
> I guess `Journal` is a custom `ParseObject` class.
> Please change
> `_queryBuilder = QueryBuilder(Journal())` to `_queryBuilder = QueryBuilder<Journal>(Journal())`
> and
> `ParseLiveListWidget(` to `ParseLiveListWidget<Journal>(`
> and
> `ParseLiveListElementSnapshot snapshot` to `ParseLiveListElementSnapshot<Journal> snapshot`.
> 
> Then try again and let me know if it made any difference.

sorry I  paste the wrong thing that how I have it in my code
`_queryBuilder = QueryBuilder<Journal>(Journal())
        ..setAmountToSkip(pageIndex)
          ..setLimit(pageLimit)
          ..whereEqualTo("user", globals.user)
          ..orderByDescending("createdAt")
          ..includeObject(["user"]);`

`ParseLiveListWidget<Journal>(
              query: _queryBuilder,
              duration: const Duration(seconds: 0),
              childBuilder: (BuildContext context, ParseLiveListElementSnapshot<Journal> snapshot) {
                if (snapshot.failed) {
                  return const Text('something went wrong!');
                } else if (snapshot.hasData) {
                  return _itemBuilder(context, snapshot);
                }
                else {
                  return CircularProgressIndicator();
                  // return const ListTile(
                  //   leading: CircularProgressIndicator(),
                  // );
                }
                
              }
             
              )`

**Comment by maaeps** [comment] 2020-03-12 19:45
@pastordee 
I think I wrote https://github.com/parse-community/Parse-SDK-Flutter/issues/330#issuecomment-598359323 a little confusing,
I didn't meant adding a "?" but changing the "1.26" to "1.0.26"



Could you perform the second and third change in https://github.com/parse-community/Parse-SDK-Flutter/issues/330#issuecomment-598356418 and give me an update?

**Comment by pastordee** [comment] 2020-03-12 20:10
@maaeps 

Sorry is the same
This is the result which is right but nothing happens in terms of updating the ParseLiveListWidget until I reload it myself.

Class: Journal
Function: ParseApiRQ.save
Status Code: 200
Payload: {"className":"Journal","objectId":"fIGAAr8Jo4","createdAt":"2019-12-08T11:21:48.429Z","updatedAt":"2020-03-12T20:04:28.170Z","user":{"__type":"Pointer","className":"_User","objectId":"3dLYgtOt11"},"journal":"Pray for Mordecai legs constantly. ","title":"Mordecai","noteCount":7,"answered":false,"ACL":{"3dLYgtOt11":{"read":true,"write":true},"*":{"read":true,"write":true}}}
╰--
flutter: LiveQuery: : Listen: {"op":"update","clientId":"345ea6bc-d47b-435b-8189-8a4202c2b299","requestId":2,"object":{"user":{"__type":"Pointer","className":"_User","objectId":"3dLYgtOt11"},"journal":"Pray for Mordecai legs constantly. ","title":"Mordecai","noteCount":7,"answered":false,"createdAt":"2019-12-08T11:21:48.429Z","updatedAt":"2020-03-12T20:04:28.170Z","ACL":{"3dLYgtOt11":{"read":true,"write":true},"*":{"read":true,"write":true}},"__type":"Object","className":"Journal","objectId":"fIGAAr8Jo4"},"original":{"user":{"__type":"Pointer","className":"_User","objectId":"3dLYgtOt11"},"journal":"Pray for Mordecai legs constantly","title":"Mordecai","noteCount":7,"answered":false,"createdAt":"2019-12-08T11:21:48.429Z","updatedAt":"2020-03-12T19:56:07.448Z","ACL":{"3dLYgtOt11":{"read":true,"write":true},"*":{"read":true,"write":true}},"__type":"Object","className":"Journal","objectId":"fIGAAr8Jo4"}}

**Comment by pastordee** [comment] 2020-03-12 20:12
@maaeps 

Thanks again for your hard work I really appreciate it and God bless

**Comment by maaeps** [comment] 2020-03-12 20:26
@pastordee 
Please put down a breakpoint in the file utils/parse_live_list.dart of the SDK inside the function `void _objectUpdated(T object) {` to see, if this function gets reached.
Or send me the code/a part of it to github@maaeps.de.

**Comment by maaeps** [comment] 2020-03-12 21:00
@pastordee 
Your _itemBuilder is pretty complex. Please try a more simple Widget (e.g. just a Text widget) for testing.
Secondly, I have created a [branch](https://github.com/maaeps/Parse-SDK-Flutter/tree/livelist_debug)  with many debug prints inside the LiveList file. Please use this branch in your project, turn OFF debugging in your parse initialization and send me the log parts starting with `ParseLiveList` (or the whole log).

**Comment by maaeps** [comment] 2020-03-12 21:29
@pastordee 
Could you please also add `key: UniqueKey(),` to your Card inside the itemBuilder?

**Comment by maaeps** [comment] 2020-03-13 11:00
@pastordee 
I think I found the problem.
There a Exception gets thrown, if ParseLiveList is used together with a Custom ParseObject.
Will be fixed soon.

**Comment by pastordee** [comment] 2020-03-13 11:05
Morning and thank you will be waiting for the update.

**Comment by maaeps** [comment] 2020-03-13 12:04
reference #335

**Comment by maaeps** [comment] 2020-03-13 12:07
@pastordee 
I created the PR #336. This should fix the problem.
You can use/try [this](https://github.com/maaeps/Parse-SDK-Flutter/tree/livelist_custom_object_fix) branch while #336 is pending.

**Comment by pastordee** [comment] 2020-03-13 12:32
> @pastordee
> I created the PR #336. This should fix the problem.
> You can use/try [this](https://github.com/maaeps/Parse-SDK-Flutter/tree/livelist_custom_object_fix) branch while #336 is pending.

It works like magic thank you so much

**Comment by maaeps** [comment] 2020-03-13 12:42
@pastordee 
Glad to hear that.
And sure.

**Closed** 2020-03-14 03:02 UTC

**Comment by pastordee** [comment] 2020-03-16 07:47
@maaeps 
Hi morning hope you had a great weekend is there any chance you will be able to work on ParseSliverlist

**Comment by maaeps** [comment] 2020-03-16 09:02
You mean to base ParseLiveListWidget on SilverList?

**Comment by pastordee** [comment] 2020-03-16 09:06
Yes

Pastor David Frimpong
Creator and founder of Prayer Circle

Prayer Circle ⭕️ allows you to pray for people leave your prayer request,  is also a prayer journal, you can create a group for you and your family, the saying is those who pray together stay together check it out

Downloaded it Today 
https://pcdl.page.link/prayers
https://prayercircle.co.uk

**Comment by pastordee** [comment] 2020-03-16 09:27
> You mean to base ParseLiveListWidget on SliverList?

or have both of them 
ParseLiveListWidget
ParseSliverListWidget

**Comment by maaeps** [comment] 2020-03-16 16:13
I've not worked with Slivers yet.
But as ParseLiveList handles all of the fetching etc., adding something based on SliverList should work.
Actually I've planed working on LiveList again. Since I am not happy with some of the scrolling behavior when adding/removing items at the top of the list. Maybe working with Slivers will provide more flexibility.

**Comment by hamidabdulmalik** [comment] 2020-04-01 23:26
This is still not working for anroid. @maaeps how did you fix it please?

**Comment by maaeps** [comment] 2020-04-02 09:44
@hamidabdulmalik 
What is "This"?
What error do you get? / What seems wrong?
Does the livelist_example work for you?
Have you enabled LiveQuery?

I am sorry, but without a clear error description, I can not help you. There are too many factors.
This issue has been closed 19 days ago, you might want to consider opening a new one. So more people would see your post.

**Comment by hamidabdulmalik** [comment] 2020-04-04 01:31
> @hamidabdulmalik
> What is "This"?
> What error do you get? / What seems wrong?
> Does the livelist_example work for you?
> Have you enabled LiveQuery?
> 
> I am sorry, but without a clear error description, I can not help you. There are too many factors.
> This issue has been closed 19 days ago, you might want to consider opening a new one. So more people would see your post.

I am sorry if my comment above is not so detailed. I mean LiveQuery in 1.0.26 is still not working, I had to fall back to version 1.0.25. There are no error messages, LiveQuery is enabled and everything, when there is a new transaction, nothing happens at all.

**Comment by pastordee** [comment] 2020-05-10 10:58
@maaeps 
Hi just a quick question how do I turn this into a grid view

**Comment by maaeps** [comment] 2020-05-10 14:48
@pastordee 
LiveList does basically handle all the logic. LiveListWidget instantiates an instance of LiveList and listens for ParseLiveListEvent events.
You should be able to build a widget similarly to LiveListWidget that builds a GridView using GridView.builder(). You can use ParseLiveListElement as it is. ParseLiveListElement is basically the LiveList equivalent in the context of a singe element. ParseLiveListElementWidget on the other hand is wont be suitable for you, I think.
The whole Widget part of LiveList seems to be complex, as I added animations. If you plan to build a GridView without any animations it might be as simple as this:
**NOT TESTED!!!**
```
class ParseLiveGridViewWidget<T extends ParseObject> extends StatefulWidget {
  const ParseLiveGridViewWidget({
    Key key,
    @required this.query,
    this.listLoadingElement,
    @required this.childBuilder,
    this.listenOnAllSubItems,
    this.listeningIncludes,
  }) : super(key: key);

  final QueryBuilder<T> query;
  final Widget listLoadingElement;

  final ChildBuilder<T> childBuilder;

  final bool listenOnAllSubItems;
  final List<String> listeningIncludes;

  @override
  _ParseLiveGridViewWidgetState<T> createState() =>
      _ParseLiveGridViewWidgetState<T>(
        query: query,
        listenOnAllSubItems: listenOnAllSubItems,
        listeningIncludes: listeningIncludes,
      );
}

class _ParseLiveGridViewWidgetState<T extends ParseObject>
    extends State<ParseLiveGridViewWidget<T>> {
  _ParseLiveGridViewWidgetState(
      {@required this.query,
      bool listenOnAllSubItems,
      List<String> listeningIncludes}) {
    ParseLiveList.create(
      query,
      listenOnAllSubItems: listenOnAllSubItems,
      listeningIncludes: listeningIncludes,
    ).then((ParseLiveList<T> value) {
      setState(() {
        _liveList = value;
        _liveList.stream.listen((ParseLiveListEvent<ParseObject> event) {
          if (event is ParseLiveListAddEvent) {
          } else if (event is ParseLiveListDeleteEvent) {}
        });
      });
    });
  }

  final QueryBuilder<T> query;
  ParseLiveList<T> _liveList;

  @override
  Widget build(BuildContext context) {
    return _liveList == null
        ? widget.listLoadingElement ?? Container()
        : buildWidget();
  }

  Widget buildWidget() {
    return GridView.builder(
      itemCount: _liveList?.size ?? 0,
      gridDelegate:
          const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
      itemBuilder: (BuildContext context, int index) {
        return ParseLiveGridViewElementWidget<T>(
          key: ValueKey<String>(_liveList?.getIdentifier(index) ?? '_NotFound'),
          stream: () => _liveList?.getAt(index),
          loadedData: () => _liveList?.getLoadedAt(index),
          childBuilder: widget.childBuilder,
        );
      },
    );
  }

  @override
  void dispose() {
    _liveList.dispose();
    _liveList = null;
    super.dispose();
  }
}

class ParseLiveGridViewElementWidget<T extends ParseObject>
    extends StatefulWidget {
  const ParseLiveGridViewElementWidget(
      {Key key, this.stream, this.loadedData, @required this.childBuilder})
      : super(key: key);

  final StreamGetter<T> stream;
  final DataGetter<T> loadedData;
  final ChildBuilder<T> childBuilder;

  @override
  _ParseLiveGridViewElementWidgetState<T> createState() {
    return _ParseLiveGridViewElementWidgetState<T>(loadedData, stream);
  }
}

class _ParseLiveGridViewElementWidgetState<T extends ParseObject>
    extends State<ParseLiveGridViewElementWidget<T>>
    with SingleTickerProviderStateMixin {
  _ParseLiveGridViewElementWidgetState(
      DataGetter<T> loadedDataGetter, StreamGetter<T> stream) {
    _snapshot = ParseLiveListElementSnapshot<T>(loadedData: loadedDataGetter());
    if (stream != null) {
      _streamSubscription = stream().listen(
        (T data) {
          if (widget != null) {
            setState(() {
              _snapshot = ParseLiveListElementSnapshot<T>(loadedData: data);
            });
          } else {
            _snapshot = ParseLiveListElementSnapshot<T>(loadedData: data);
          }
        },
        onError: (Object error) {
          if (error is ParseError) {
            if (widget != null) {
              setState(() {
                _snapshot = ParseLiveListElementSnapshot<T>(error: error);
              });
            } else {
              _snapshot = ParseLiveListElementSnapshot<T>(error: error);
            }
          }
        },
        cancelOnError: false,
      );
    }
  }

  ParseLiveListElementSnapshot<T> _snapshot;

  StreamSubscription<T> _streamSubscription;

  @override
  void dispose() {
    _streamSubscription?.cancel();
    _streamSubscription = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.childBuilder(context, _snapshot);
  }
}
```

**Comment by ZeroNilZero** [comment] 2020-07-18 23:08
@maaeps why it load each results separately?
how can we get them all at once?
and dose it automatically dispose?

**Comment by maaeps** [comment] 2020-08-05 14:19
@ZeroNilZero 
The lazy loading is implemented to show long lists as quick as possible.However, for short lists this takes longer than loading them instantly.
I have implemented a function for turning off lazy loading. #407 But it has not been tested that much, yet.

**Comment by AsyraniAzni** [comment] 2021-06-12 02:35
> I've not worked with Slivers yet.
> But as ParseLiveList handles all of the fetching etc., adding something based on SliverList should work.
> Actually I've planed working on LiveList again. Since I am not happy with some of the scrolling behavior when adding/removing items at the top of the list. Maybe working with Slivers will provide more flexibility.

Sorry, maybe I miss something. Have you done implemented ParseLiveSliverListWidget? I did not find any reference. Sorry, if I miss something
